name: ray_repair
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - pytorch-cuda=12.1
  - numpy>=1.24
  - scipy
  - openexr-python
  - opencv
  - pip
  - pip:
      - lpips
      - tqdm
      - tensorboard
      - onnx
      - huggingface_hub
      - datasets
